# Generated by Django 5.1.7 on 2025-03-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trip_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
